name: ci

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
      CI: on
      GO111MODULE: on
    steps:
    - uses: actions/checkout@v2
      with:
        path: ./src/github.com/${{ github.repository }}
    - uses: actions/setup-go@v1
      with:
        go-version: '1.14'    
    - run: pwd
    - run: go test -v -race -failfast --cover -covermode=atomic -mod=vendor -coverprofile=coverage.txt .
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        file: ./coverage.txt
